pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-northeast-2'
        GIT_REPOSITORY_URL = 'https://github.com/cherrypic-proj/cherrypic-server.git'
        ECR_REGISTRY = '805472282514.dkr.ecr.ap-northeast-2.amazonaws.com'
        ECR_REPOSITORY = 'cherrypic-api'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('init') {
            steps {
                deleteDir()
            }
        }

        stage('Clone repository') {
            steps {
                git branch: "develop",
                url: "${GIT_REPOSITORY_URL}"
            }
        }
        
        stage('Build API') {
            steps {
                sh './gradlew :cherrypic-api:clean build -x test'
            }
        }
        
        stage('Build API Image') {
            steps {
                script {
                    image = docker.build("${ECR_REPOSITORY}:${IMAGE_TAG}", "cherrypic-api")
                }
            }
        }

        stage('Push API image to ECR') {
            steps {
                script {
                    docker.withRegistry("https://${ECR_REGISTRY}/${ECR_REPOSITORY}:", "ecr:ap-northeast-2:aws-credentials") {
                        image.push("${IMAGE_TAG}")
                    }
                }
            }
        }
        
        stage('Prune Docker Images') {
            steps {
                sh "docker image prune -a -f"
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'cherrypic-was-dev',
                            transfers: [
                                sshTransfer(
                                    execCommand: """
                                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                                    docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
                                    docker rm -f cherrypic-api || true
                                    docker run -d --name cherrypic-api --env-file .env -p 8080:8080 ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
                                    docker image prune -a -f
                                    """
                                )
                            ]
                        )
                    ]
                )
            }
        }
    }
}